#!/bin/sh

# Geardroid App Installer
# Copyright 2015 Dani Gearbench
#
#
# Requires: sha256sum, curl, GnuPG/GPG, Java Runtime
#	    fastboot, adb.
#
# Web: http://gearbench.uk   Mail: dani@gearbench.uk
# Twitter: @DaniGearbench    Complaints: /dev/null
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

CWMTOUCHURL="http://download2.clockworkmod.com/recoveries/recovery-clockwork-touch-6.0.4.7-flo.img"
CWMURL="http://download2.clockworkmod.com/recoveries/recovery-clockwork-6.0.4.7-flo.img"

echo "Geardroid App Installer requires ClockworkMod Recovery."
echo "This installer can download CWM for Nexus 7 2013 (wifi) [flo]"

copy_geardroid() {
	read -p "Please enable USB debugging, connect Nexus 7 then press [enter]..." 2>/dev/null
	adb push update-SIGNED.zip /sdcard/
}

install_cwm() {
	copy_geardroid
	curl -s -L -o cwm.img $CWMTOUCHURL
	echo "Rebooting into bootloader..."
	adb reboot bootloader
	sleep 5s
	echo "Installing recovery image..."
	fastboot flash recovery cwm.img
	echo "\n\rPlease reboot into bootloader by holding VOLUME DOWN and POWER"
	echo "Then select Recovery from the menu to continue"
}

install_geardroid() {
		copy_geardroid;
		echo "Rebooting into recovery..."
		adb reboot recovery
}

while true; do
    read -p "Would you like to install CWM Recovery Flo? (y/n) " yn
    case $yn in
        [Yy]* ) install_cwm; break;;
        [Nn]* ) install_geardroid; break;;
        * ) echo "Please answer yes or no.";;
    esac
done



echo "\n\rFrom the recovery menu: \n->select install zip \n-> choose zip from /sdcard \n-> update-SIGNED.zip\n\r"
echo "After the script finishes, reboot your Nexus 7 and you're done!"
echo "Remember to configure Tor, i2p and/or Bitmask before exposing yourself to the internets."
echo "\n\rAll complaints to dani@gearbench.uk, @DaniGearbench or /dev/null\n\r"
